// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorld.Api.Data;

#nullable disable

namespace SportsWorld.Api.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251211_AddAmountBorrowedToFinance")]
    partial class AddAmountBorrowedToFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SportsWorld.Api.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountBorrowed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneyLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneySpent")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");
                });
#pragma warning restore 612, 618
        }
    }
}
