<<<<<<< HEAD:backend/SportsWorld.Api/Migrations/20251211_AddAmountBorrowedToFinance.Designer.cs
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorld.Api.Data;

#nullable disable

namespace SportsWorld.Api.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251211_AddAmountBorrowedToFinance")]
    partial class AddAmountBorrowedToFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SportsWorld.Api.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountBorrowed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneyLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneySpent")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");
                });
#pragma warning restore 612, 618
        }
    }
}
=======
﻿// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorld.Api.Data;

#nullable disable

namespace SportsWorld.Api.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251202125803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SportsWorld.Api.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PurchaseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
>>>>>>> 4b8de206eaac6cd1dc0b304e2c393bd0539318e8:backend/SportsWorld.Api/Migrations/20251202125803_InitialCreate.Designer.cs
