// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorld.Api.Data;

#nullable disable

namespace SportsWorld.Api.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251214172306_AddAthleteFields")]
    partial class AddAthleteFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SportsWorld.Api.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PurchaseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Male",
                            Image = "https://example.com/messi.jpg",
                            Name = "Lionel Messi",
                            Nationality = "",
                            Position = "",
                            Price = 100,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 2,
                            Gender = "Male",
                            Image = "https://example.com/ronaldo.jpg",
                            Name = "Cristiano Ronaldo",
                            Nationality = "",
                            Position = "",
                            Price = 95,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 3,
                            Gender = "Male",
                            Image = "https://example.com/haaland.jpg",
                            Name = "Erling Haaland",
                            Nationality = "",
                            Position = "",
                            Price = 90,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 4,
                            Gender = "Male",
                            Image = "https://example.com/mbappe.jpg",
                            Name = "Kylian Mbappé",
                            Nationality = "",
                            Position = "",
                            Price = 92,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 5,
                            Gender = "Female",
                            Image = "https://example.com/ada-hegerberg.jpg",
                            Name = "Ada Hegerberg",
                            Nationality = "",
                            Position = "",
                            Price = 88,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 6,
                            Gender = "Female",
                            Image = "https://example.com/alexia.jpg",
                            Name = "Alexia Putellas",
                            Nationality = "",
                            Position = "",
                            Price = 89,
                            PurchaseStatus = false
                        });
                });

            modelBuilder.Entity("SportsWorld.Api.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MoneyLeft")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneySpent")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("SportsWorld.Api.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });
#pragma warning restore 612, 618
        }
    }
}
